OpenAPI: Fix typo in implementation to match generated API function.
```
-*- mode: compilation; default-directory: "~/github_repos/go_noodling/use_openapi_generated_server/" -*-
Compilation started at Wed Jul 26 10:53:36

go build -v && go test -v && go vet && go run .
go_noodling/use_openapi_generated_server
./main.go:45:26: cannot use petStore (variable of type *api.PetStore) as api.ServerInterface value in argument to api.RegisterHandlers: *api.PetStore does not implement api.ServerInterface (missing method FindPetById)
		have FindPetByID(echo.Context, int64) error
		want FindPetById(echo.Context, int64) error

Compilation exited abnormally with code 1 at Wed Jul 26 10:53:36
```