OpenAPI: pick an unused port.
Before:

```
-*- mode: compilation; default-directory: "~/github_repos/go_noodling/use_openapi_generated_server/" -*-
Compilation started at Wed Jul 26 10:53:36

go build -v && go test -v && go vet && go run .
go_noodling/use_openapi_generated_server
./main.go:45:26: cannot use petStore (variable of type *api.PetStore) as api.ServerInterface value in argument to api.RegisterHandlers: *api.PetStore does not implement api.ServerInterface (missing method FindPetById)
		have FindPetByID(echo.Context, int64) error
		want FindPetById(echo.Context, int64) error

Compilation exited abnormally with code 1 at Wed Jul 26 10:53:36
```

After:

```
-*- mode: compilation; default-directory: "~/github_repos/go_noodling/use_openapi_generated_server/" -*-
Compilation started at Wed Jul 26 10:55:08

go build -v && go test -v && go vet && go run .
go_noodling/use_openapi_generated_server
?   	go_noodling/use_openapi_generated_server	[no test files]

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.11.1
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on [::]:8083
```